### ISSUE TITLE
Open-sourcing

### ISSUE THREAD

**Issue by stephanedaviet** [BOOKEEN/kernel-linux-3.0#1]
I see that this repository is quite new. I'm looking for an e-reader and quite versed in open-source. Is there a will from Bookeen to publish other parts of its readers (BooReader for instance)? Having a really opened stack would be a real plus in the current market for some customers. Moreover, it will also pave the way for external contribution of some interested users.

**Comment by ghost** [comment]
So far, nothing has been decided about open-sourcing the reader app.
But porting  things like koreader (https://github.com/koreader/koreader) wouldn't be hard, using informations of these two files : drv_display_sun4i.h and dev_disp.c.

The most important thing here is the ioctl command `DISP_CMD_EINK_UPDATE`, which updates the eInk screen. You can also change the screen modes using the enum `__eink_update_mode`.

**Comment by stephane-daviet-maif** [comment]
I didn't know KOReader. Seems nice. Probably a relative amount of work needed to get it to work under Bookeen.

I still second my first ask and really hope you will get your BooReader open-sourced.

Thanks for your response.
