### ISSUE TITLE
Linux License is incorrect

### ISSUE THREAD

**Issue by Godzil** [BOOKEEN/kernel-linux-3.0#3]
The linux kernel is under GPL v2 **only** and can't be changed into GPL v3

Cf: https://en.wikipedia.org/wiki/Linux_kernel#Licensing_terms

> The Linux kernel is licensed explicitly only under version 2 of the GPL, without offering the licensee the option to choose "any later version"

Also the license is in the COPYING file, so the (incorrect) LICENSE file should not even exit.

**Comment by ghost** [comment]
Send a PR.
